### ISSUE TITLE
No logo provided for module. 

### ISSUE THREAD

**Issue by ghost** [CCV/ccvonlinepayments-prestashop#1]
The module does not have a logo.png in it base folder (/modulename/logo.png).

![img](https://user-images.githubusercontent.com/17967576/117926450-155dc600-b2f9-11eb-9c67-8d8fa380e2d1.png)

**Comment by ghost** [comment]
![logo](https://user-images.githubusercontent.com/17967576/117926612-52c25380-b2f9-11eb-9334-d895f73f29e4.png)

**Comment by Basvaanholt** [comment]
Thanks for reporting. we have fixed this issue in a new release.
